# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: 'pskdev'
  imageName: 'backend'

steps:
  - script: |
      docker build -t repo.treescale.com/$(imageName) .
      docker login -u $(dockerId) -p $(dockerPassword) repo.treescale.com
      docker push repo.treescale.com/$(imageName)/$(imageName)
    env:
      pswd: $(dockerPassword)