version: '3'
services:

  backend:
    image: pskdev.azurecr.io/backend:latest
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=demo
    ports:
      - 8080:8080
  fe:
    image: pskdev.azurecr.io/frontend:latest
    container_name: fe
    ports:
      - 80:80
  db:
    image: mongo:4.0
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

volumes:
  db_mongo_data:
    driver: local