version: '3'
services:

  fe:
    image: repo.treescale.com/pskdev/frontend:latest
    container_name: be_frontend
    network_mode: "host"
    ports:
      - 4200:4200
    volumes:
        - ./nginx-for-dev.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mongo:4.0
    container_name: be_db
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

volumes:
  db_mongo_data:
    driver: local