version: '3'
services:

  fe:
    image: pskdev.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - 4200:80
    volumes:
      - ./nginx-for-dev.conf:/etc/nginx/nginx.conf:ro
  db:
    image: mongo:4.0
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

volumes:
  db_mongo_data:
    driver: local