version: '3'
services:

  fe:
    image: repo.treescale.com/pskdev/pskdev/frontend:latest
    container_name: psk_frontend
    ports:
      - 4200:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
  db:
    image: mongo:4.0
    container_name: fe_db
    ports:
      - 27017:27017
    volumes:
      - db_mongo_data:/data/db

volumes:
  db_mongo_data:
    driver: local