version: '3'
services:

  backend:
    image: repo.treescale.com/pskdev/backend:latest
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    volumes:
      - /var/log/psk:/var/log
  fe:
    image: repo.treescale.com/pskdev/frontend:latest
    container_name: fe
    ports:
      - 80:80
  db:
    image: mongo:4.0
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - /data/mongo:/data/db
