spring:
  data:
    mongodb:
      host: db
      port: 27017
app:
  security:
    oauth2:
      swagger:
        redirect-uri: http://ec2-18-188-16-88.us-east-2.compute.amazonaws.com:8080/api/webjars/springfox-swagger-ui/oauth2-redirect.html