spring:
  data:
    mongodb:
      database: psk-db
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testinis.pastininkas@gmail.com
    password: asAS12!@
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

logging:
  file: /var/log/psk-debug.log
  level:
    com.psk.backend: DEBUG

server:
  servlet:
    context-path: /api

app:
  security:
    jwt:
      key: mif-psk-key
    oauth2:
      web:
        client: mif-psk
        secret: mif-psk-secret
      swagger:
        client: swagger
        secret: swagger-secret
        redirect-uri: http://localhost:8080/api/webjars/springfox-swagger-ui/oauth2-redirect.html

  url: http://localhost:4200
