spring:
  data:
    mongodb:
      host: 13.86.236.76
      port: 27017

app:
  security:
    oauth2:
      swagger:
        redirect-uri: https://pskdemo.azurewebsites.net/api/webjars/springfox-swagger-ui/oauth2-redirect.html
